export const UPDATE_PARAM_VALUE = "UPDATE_PARAM_VALUE"
export const SET_MODEL_VALUES_TO_RESEARCHER_VALUES = "SET_MODEL_VALUES_TO_RESEARCHER_VALUES"

export const SET_MODEL_VALUES_TO_MEAN = 'SET_MODEL_VALUES_TO_MEAN'
export const SET_MODEL_VALUES_TO_MEDIAN = 'SET_MODEL_VALUES_TO_MEDIAN'